version = 1

[envs.chezmoi]
channels = ["conda-forge"]
dependencies = { chezmoi = "*" }
exposed = { chezmoi = "chezmoi" }

[envs.starship]
channels = ["conda-forge"]
dependencies = { starship = "*" }
exposed = { starship = "starship" }

[envs.tree]
channels = ["conda-forge"]
dependencies = { tree = "*" }
exposed = { tree = "tree" }

[envs.tldr]
channels = ["conda-forge"]
dependencies = { tldr = "*" }
exposed = { tldr = "tldr" }

[envs.direnv]
channels = ["conda-forge"]
dependencies = { direnv = "*" }
exposed = { direnv = "direnv" }

[envs.bat]
channels = ["conda-forge"]
dependencies = { bat = "*" }
exposed = { bat = "bat" }

[envs.uv]
channels = ["conda-forge"]
dependencies = { uv = "*" }
exposed = { uv = "uv", uvx = "uvx" }

[envs.xsv]
channels = ["conda-forge"]
dependencies = { xsv = "*" }
exposed = { xsv = "xsv" }

[envs.graphviz]
channels = ["conda-forge"]
dependencies = { graphviz = "*" }
exposed = { ".graphviz-post-link" = ".graphviz-post-link", acyclic = "acyclic", bcomps = "bcomps", ccomps = "ccomps", circo = "circo", cluster = "cluster", diffimg = "diffimg", dijkstra = "dijkstra", dot = "dot", dot2gxl = "dot2gxl", dot_builtins = "dot_builtins", dot_sandbox = "dot_sandbox", edgepaint = "edgepaint", fdp = "fdp", gc = "gc", gml2gv = "gml2gv", graphml2gv = "graphml2gv", gv2gml = "gv2gml", gv2gxl = "gv2gxl", gvcolor = "gvcolor", gvgen = "gvgen", gvmap = "gvmap", gvpack = "gvpack", gvpr = "gvpr", gxl2dot = "gxl2dot", gxl2gv = "gxl2gv", mm2gv = "mm2gv", neato = "neato", nop = "nop", osage = "osage", patchwork = "patchwork", prune = "prune", sccmap = "sccmap", sfdp = "sfdp", tred = "tred", twopi = "twopi", unflatten = "unflatten" }

[envs.htop]
channels = ["conda-forge"]
dependencies = { htop = "*" }
exposed = { htop = "htop" }

[envs.btop]
channels = ["conda-forge"]
dependencies = { btop = "*" }
exposed = { btop = "btop" }

[envs.nvtop]
channels = ["conda-forge"]
dependencies = { nvtop = "*" }
exposed = { nvtop = "nvtop" }

[envs.gh]
channels = ["conda-forge"]
dependencies = { gh = "*" }
exposed = { gh = "gh" }
